### ISSUE TITLE
upgrade to mio 0.7

### ISSUE THREAD

**Issue by asafigan** [notify-rs/notify#248]
New version of mio is out. Old version relies on a deprecated crate (net2).

**Comment by JohnTitor** [comment]
The problem here is that mio-extras also depends on mio 0.6. We should take care of that crate first.

**Comment by extrawurst** [comment]
that does not seem to happen: https://github.com/dimbleby/mio-extras/issues/7 looks like other major crates like `winit` rather move away from `mio-extras`. is that a feasible option?

**Comment by JohnTitor** [comment]
I'm in favor of either. Anyway, we should implement our own `channel` (or re-use `crossbeam-channel`?). In addition, we could also remove `mio` itself, though it'll be hard rework.

**Comment by extrawurst** [comment]
this thing lingering for a while, I think first a simpler and quicker solution and maybe followup with a more involved but nicer one later (but you know the codebase better)

**Comment by JohnTitor** [comment]
> I think first a simpler and quicker solution and maybe followup with a more involved but nicer one later (but you know the codebase better)

Agreed.

I'm not sure I have some time to look into this in the near future, so any contributions are welcome =)

**Comment by extrawurst** [comment]
Ok I have checked for some reason, the lib already uses both a channel from `mio-extras` and `crossbeam-channel`. I could give it a go in removing `mio-extras`. would you accept a PR for that?

**Comment by JohnTitor** [comment]
> I could give it a go in removing mio-extras. would you accept a PR for that?

Sure!

**Comment by extrawurst** [comment]
@JohnTitor ok not gonna happen, I just realize how tightly coupled mio is to their custom channels :(

**Comment by JohnTitor** [comment]
Yep, we should have our own items as mentioned above. Thanks for trying anyway!

**Comment by Turakar** [comment]
Hi, I just wanted to let you know that this triggers `cargo deny` and `cargo audit` on other repos, like [rocket](https://github.com/SergioBenitez/Rocket/issues/1440), due to [RUSTSEC-2020-0016](https://rustsec.org/advisories/RUSTSEC-2020-0016) which gets resolved by this update according to this [thread over at mio](https://github.com/tokio-rs/mio/issues/1319). I do understand that this is a bigger change though. Unfortunately, I do not have the time to implement it either :frowning_face:
