### ISSUE TITLE
Migrate CI from Travis to other CI, possibly GHA

### ISSUE THREAD

**Issue by JohnTitor** [notify-rs/notify#271]
Travis has now restricted their free bandwidth so I think we could consider migrating to other CI.
See https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing for more details.

**Comment by 0xpr03** [comment]
So macOS is the problem, I see.
I'd currently not migrate to github actions if we plan to include any secrets for deploying to crates.io due to [github CVEs](https://bugs.chromium.org/p/project-zero/issues/detail?id=2070&can=2&q=&colspec=ID%20Type%20Status%20Priority%20Milestone%20Owner%20Summary&cells=ids)

**Comment by JohnTitor** [comment]
> So macOS is the problem, I see.

No, the change affects all the builds. They introduced a new billing model. If our free credit is running out, we cannot use Travis in that month IIUC.

**Comment by 0xpr03** [comment]
No I don't we do. I mean that on macOS the limitations are created. I have no objections with moving to GH Actions.
