### ISSUE TITLE
ModifyKind does not derive Copy

### ISSUE THREAD

**Issue by jasonheath** [notify-rs/notify#458]
Apologies if I should ask this in a different place but I think the issues section is correct for this project.  I've noticed that ModifyKind doesn't derive Copy. Based on a quick visual inspection I believe that all of its peer enums and the enums it makes use of derive Copy.  Is there a reason it doesn't?  If there isn't I can submit a pull request that derives copy.

**Comment by 0xpr03** [comment]
Yeah there is currently no real blocker for deriving copy on top of clone. But it also will make it impossible to remove, if for any reason we should want a bigger sub type / value later on. But I could be too restrictive in favor of unknown unknowns.

Is there a good use case for making it copy ?

**Comment by dfaust** [comment]
> Is there a good use case for making it copy ?

When matching on `ModifyKind`, it is moved into the match and so the event cannot be used anymore.
I believe it should be `Copy` just like the other enums, so that this use case is easier and the API is more uniform.

![grafik](https://user-images.githubusercontent.com/893710/234108431-87bb6991-893b-4ee6-9d0a-81129cf66005.png)

**Comment by 0xpr03** [comment]
I would suggest matching over &event. Still, I would merge a PR for this.
